spring.application.name=test_app_apring
# テンプレートの保存場所
spring.thymeleaf.prefix=classpath:/templates/
# テンプレートファイルの拡張子
spring.thymeleaf.suffix=.html
# テンプレートモード
spring.thymeleaf.mode=HTML
# テンプレートのエンコーディング
spring.thymeleaf.encoding=UTF-8
# キャッシュの無効化（開発時）
spring.thymeleaf.cache=false
# Thymeleafのバージョンチェックを無効化（パフォーマンス向上）
spring.thymeleaf.check-template=false
spring.thymeleaf.check-template-location=false

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.datasource.url=jdbc:postgresql://db:5432/spring_boot_development
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
logging.level.org.hibernate.type.EnumType=trace

spring.messages.basename=i18n/messages, i18n/ValidationMessages
spring.web.locale=ja_JP
spring.web.locale-resolver=fixed

# MyBatis
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.example.test_app_apring.domain.user.model
logging.level.com.example=debug
